<?php
/**
 * @file
 * job_opening.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function job_opening_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['job_opening-jobopening_apply'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jobopening_apply',
    'module' => 'job_opening',
    'node_types' => array(
      0 => 'job_opening',
    ),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
